language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

env:
    - DJANGO="Django==1.11.*"
    - DJANGO="Django==2.1.*"
    - DJANGO="Django==2.2.*"

install:
    - pip install -r requirements.txt
    # Removing Django
    - pip uninstall -y Django
    # Installing actual version of Django
    - pip install $DJANGO
    # Extra
    - pip install virtualenv coveralls

script:
    - cd oilandrope/ && pytest

after_success:
    - coveralls