language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

env:
    - DJANGO="Django==1.11.*"
    - DJANGO="Django==2.1.*"
    - DJANGO="Django==2.2.*"

install:
    - pip install virtualenv coveralls
    - pip install pytest pytest-django model_bakery
    - pip install $DJANGO

script:
    - cd oilandrope/ && pytest

after_success:
    - coveralls