language: python

services:
  - postgresql


python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_SETTINGS_MODULE="oilandrope.settings"

install:
  - pip install -r requirements/requirements-develop.txt
  # Extra
  - pip install coveralls

before_script:
  - psql -c 'create database oilandrope;' -U postgres

script:
  - pytest --ds $DJANGO_SETTINGS_MODULE

after_success:
  - coveralls