language: python

services:
  - postgresql


python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_SETTINGS_MODULE="oilandrope.settings"

install:
  - pip install -r requirements/requirements-develop.txt
  # Extra
  - pip install codecov pytest-cov

before_script:
  - psql -c 'create database oilandrope;' -U postgres
  # Fixing isort on migrations
  - isort -sk ./**/migrations/*.py

script:
  - python runtests.py --coverage

after_success:
  - codecov -e DJANGO_SETTINGS_MODULE
